dist: trusty
sudo: required
language: node_js
node_js:
- 10.8
addons:
  sonarcloud:
    organization: "gautamkrishnar-github"
    token:
      secure: "OglEzYSl1dBdukJvxChwVrk1BGqzf0sgKlrBEQYBHrrqCAReM7qhfG+q1wBPBVMdIh2iN46DoLBQyraM5ejyoW56VDCUn4/u4PGXomW9wGDSAjFXQruE8URDzzIBQuLYd9bG29JaIg3lSByKY2LpRifUdmdK/u47ru03dh6+EgT+8pjdR+GGgwS3qvCgTSVfD6cVepkpxoL2Bf3FgtCrYfxFHVb/tim0FsyAzDJIqQvHqhf5od+0KHjKSRKkGmKVSnq3lh1VFkxBwuoqRp28OUUbsifptVMLjVA90AA551QEHvviXaEoiW2yHbw5r+/Ee/pmGfQLsQw4EzyCYgHgW8res7qWIy0Elz2PTdWy5V893gE8ILvI8jfnuyLuISMVhO/1kxYaSELa3FcbByqtmv+OT+ibaYQXZ4768ip3la5G2ggszIdhLn8fH0Ay5opgFT79GRzP6+I6n18Z4qijy+jhdNJkqeOUX+7dw3jCn8wjM0U5gccxL422f5KkbtttMBDYrvwx7bi6T0ziurPvXjjdXYMq8UbC8CnsLeaEdFGLKgO/i8lM15/1Sdpm1xsLPn/FVZkzCsPSH2SDv00d5FPvA9YaIBTz4T0xoaZpQyt3WT64U9OelAGMQLBamZVOsc4D3ce5t0459fVizXPhCi4avaRiWm489wvVSpGpPoQ="

jdk:
- oraclejdk8
branches:
  only:
  - gh-pages
  - master
  - develop
cache:
  # cache both npm modules and Cypress binary
  directories:
  - '$HOME/.sonar/cache'
  - ~/.npm
  - ~/.cache
  # install dependencies and check that Cypress can run
  override:
  - npm ci
  - npm run cy:verify

script:
- sonar-scanner || true # Ignore sonar-scanner
- npm run test
- kill $(jobs -p) || true
